### PR TITLE
Fix show screenshot on readme

### PR DESCRIPTION
**Pull request by gildasio**
Fix show screenshot on readme

### CODE REVIEW

**Comment by fxn** [comment]
The URL to clone the repo is correct as is. On the other hand, could you please remove the leading "./"s? That is, better just "img/c.jpg" than "./img/c.jpg".

**Comment by gildasio** [comment]
So, here [1], screenshot doesn't showed, but here [2], do.

Yep, removed "./"s. Thanks for tip.

[1] - https://github.com/fxn/vim-monochrome/blob/master/README.md
[2] - https://github.com/gjuniioor/vim-monochrome/blob/master/README.md

**Comment by fxn** [comment]
The URL to clone is still patched? It is an overlook maybe?

**Comment by gildasio** [comment]
No more. I removed "./"s. Something else?

**Comment by fxn** [comment]
I mean, are you aware that the patch changes

```
git clone https://github.com/fxn/vim-monochrome.git
```

to

```
git clone https://github.com/fxn/vim-monochrome.it
```

?

**Comment by gildasio** [comment]
I don't know about this. Have a link notice about?

I use `git clone https://github.com/fxn/vim-monochrome`, work fine too.

**Comment by fxn** [comment]
If you look at the top of the page, below the header, you'll see three tabs related to this pull request: "Conversation", "Commits", and "Files changed".

The tab "Files changed" shows the patch. You'll see there that the cloning URL is being changed, as shown in my previous comment. It was probably accidentally changed in this commit https://github.com/gjuniioor/vim-monochrome/commit/60bb27b346d9df34b49ac21db5753d3ce9711403.

You need to revise the pull request not to include that change.

**Comment by gildasio** [comment]
Ow! Sorry and thanks a lot!

I think so now it's ok ;)

**Comment by fxn** [comment]
Awesome, thanks!

**Pull request merged**
