### PR TITLE
Add ColorColumn colors

### PR DESCRIPTION
**Pull request by raphael**
Use same colors as "CursorLine".

### CODE REVIEW

**Comment by fxn** [comment]
Could you please edit https://github.com/fxn/vim-monochrome/blob/master/bin/generate.rb and generate?

**Comment by raphael** [comment]
Done in #4

**Comment by raphael** [comment]
I don't have ruby installed though so would appreciate if you could generate...

**Comment by fxn** [comment]
Will do!

**Comment by fxn** [comment]
Done in f91c9849cb45dd48f57c914f6f556716a92d37f8.

**Comment by raphael** [comment]
thanks!

**Pull request closed without merging**
